ifneq (,$(filter doriot_wot_cl,$(USEMODULE)))

	USEMODULE += netdev_default
	USEMODULE += auto_init_gnrc_netif
	USEMODULE += gnrc_ipv6_default
	USEMODULE += gcoap
	USEMODULE += od
	USEPKG += tinycbor
	USEMODULE += tinycbor_float	
	USEMODULE += hashes
	USEMODULE += crypto_aes_256
	USEPKG += micro-ecc

endif

